import "dotenv/config";
import appJson from "./app.json";

const getValue = (...names) => {
  for (const name of names) {
    if (process.env[name]) return process.env[name];
  }
  return undefined;
};

const extras = {
  EXPO_PUBLIC_OPENAI_KEY: getValue("EXPO_PUBLIC_OPENAI_KEY"),
  EXPO_PUBLIC_OR_KEY: getValue("EXPO_PUBLIC_OR_KEY"),
  EXPO_PUBLIC_PAYMOB_API_BASE: getValue("EXPO_PUBLIC_PAYMOB_API_BASE", "PAYMOB_API_BASE"),
  EXPO_PUBLIC_PAYMOB_API_KEY: getValue("EXPO_PUBLIC_PAYMOB_API_KEY", "PAYMOB_API_KEY"),
  EXPO_PUBLIC_PAYMOB_IFRAME_ID: getValue("EXPO_PUBLIC_PAYMOB_IFRAME_ID", "PAYMOB_IFRAME_ID"),
  EXPO_PUBLIC_PAYMOB_CARD_INTEGRATION_ID: getValue(
    "EXPO_PUBLIC_PAYMOB_CARD_INTEGRATION_ID",
    "PAYMOB_CARD_INTEGRATION_ID"
  ),
  EXPO_PUBLIC_PAYMOB_WALLET_INTEGRATION_ID: getValue(
    "EXPO_PUBLIC_PAYMOB_WALLET_INTEGRATION_ID",
    "PAYMOB_WALLET_INTEGRATION_ID"
  ),
  EXPO_PUBLIC_PAYPAL_BASE: getValue("EXPO_PUBLIC_PAYPAL_BASE", "PAYPAL_BASE"),
  EXPO_PUBLIC_PAYPAL_CLIENT_ID: getValue("EXPO_PUBLIC_PAYPAL_CLIENT_ID", "PAYPAL_CLIENT_ID"),
  EXPO_PUBLIC_PAYPAL_SECRET: getValue("EXPO_PUBLIC_PAYPAL_SECRET", "PAYPAL_SECRET"),
  EXPO_PUBLIC_PAYPAL_CURRENCY: getValue("EXPO_PUBLIC_PAYPAL_CURRENCY", "PAYPAL_CURRENCY"),
  EXPO_PUBLIC_FIREBASE_API_KEY: getValue("EXPO_PUBLIC_FIREBASE_API_KEY", "FIREBASE_API_KEY"),
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: getValue("EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN", "FIREBASE_AUTH_DOMAIN"),
  EXPO_PUBLIC_FIREBASE_PROJECT_ID: getValue("EXPO_PUBLIC_FIREBASE_PROJECT_ID", "FIREBASE_PROJECT_ID"),
  EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET: getValue(
    "EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET",
    "FIREBASE_STORAGE_BUCKET"
  ),
  EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: getValue(
    "EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
    "FIREBASE_MESSAGING_SENDER_ID"
  ),
  EXPO_PUBLIC_FIREBASE_APP_ID: getValue("EXPO_PUBLIC_FIREBASE_APP_ID", "FIREBASE_APP_ID"),
  EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID: getValue(
    "EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID",
    "FIREBASE_MEASUREMENT_ID"
  ),
};

export default () => ({
  ...appJson,
  expo: {
    ...appJson.expo,
    extra: extras,
  },
});
